---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tor.fulvio.dev
  resources:
  - tornetworkconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tor.fulvio.dev
  resources:
  - tornetworkconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - tor.fulvio.dev
  resources:
  - tornetworkconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tor.fulvio.dev
  resources:
  - tornetworksidecarcontrollerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tor.fulvio.dev
  resources:
  - tornetworksidecarcontrollerconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - tor.fulvio.dev
  resources:
  - tornetworksidecarcontrollerconfigs/status
  verbs:
  - get
  - patch
  - update
