# permissions for end users to view TorConfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: torproxy
    app.kubernetes.io/managed-by: kustomize
  name: TorConfig-viewer-role
rules:
- apiGroups:
  - tor.fulvio.dev
  resources:
  - TorConfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tor.fulvio.dev
  resources:
  - TorConfigs/status
  verbs:
  - get
