# permissions for end users to view TorBridgeConfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: torproxy
    app.kubernetes.io/managed-by: kustomize
  name: TorBridgeConfig-viewer-role
rules:
- apiGroups:
  - tor.fulvio.dev
  resources:
  - TorBridgeConfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tor.fulvio.dev
  resources:
  - TorBridgeConfigs/status
  verbs:
  - get
