# permissions for end users to edit tornetworksidecarcontrollerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: torproxy
    app.kubernetes.io/managed-by: kustomize
  name: tornetworksidecarcontrollerconfig-editor-role
rules:
- apiGroups:
  - tor.fulvio.dev
  resources:
  - tornetworksidecarcontrollerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tor.fulvio.dev
  resources:
  - tornetworksidecarcontrollerconfigs/status
  verbs:
  - get
