# permissions for end users to edit tornetworkconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tor-on-your-side
    app.kubernetes.io/managed-by: kustomize
  name: tornetworkconfig-editor-role
rules:
- apiGroups:
  - tor.fulvio.dev
  resources:
  - tornetworkconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tor.fulvio.dev
  resources:
  - tornetworkconfigs/status
  verbs:
  - get
