apiVersion: tor.fulvio.dev/v1alpha1
kind: TorNetworkSidecarControllerConfig
metadata:
  labels:
    app.kubernetes.io/name: torproxy
    app.kubernetes.io/managed-by: kustomize
  name: tornetworksidecarcontrollerconfig-sample
spec:
  # TODO(user): Add fields here
