apiVersion: tor.fulvio.dev/v1alpha1
kind: TorNetworkConfig
metadata:
  name: example-config
spec:
  defaultExitNodes:
    - country: 'us'
    - country: 'de'
  hiddenServices:
    - hostname: 'example1.onion'
      targetPort: 80
    - hostname: 'example2.onion'
      targetPort: 443
  metricsEnabled: true
