apiVersion: tor.fulvio.dev/v1alpha1
kind: TorBridgeConfig
metadata:
  name: my-torbridgeconfig
spec:
  relayType: "bridge"
  orPort: 9001
  dirPort: 9030
  image: "torproject/tor:latest"
  contactInfo: "admin@example.com"
  nickname: "MyTorBridge"
  serverTransportPlugin: "obfs4"
  serverTransportListenAddr: "0.0.0.0:9002"
  extOrPort: "auto"
  originPort: 9003
  redirectPort: 9004